[build]
  publish = "dist" # Ajusta esto a tu carpeta de construcción si es diferente
  command = "npm run build"


[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
NODE_VERSION = "22"